### ISSUE TITLE
<<: & * in docker-compose

### ISSUE THREAD

**Issue by PhVHoang** [PhVHoang/TIL#110]
`<<` is called the YAML merge key.
In this code snippet, we merge keys and values from `foo` to `bar` but override the `key2` to a new value. And we add a new key-value pair to `bar`.

Now bar has the following value: `{"bar": {"key1": "val1", "key2": val2-new", "key3": "val3"}}.`
```yaml
foo: &myanchor
  key1: "val1"
  key2: "val2"

bar:
  << : *myanchor
  key2: "val2-new"
  key3: "val3"
```

## References
1. https://stackoverflow.com/questions/50072810/whats-the-double-arrow-django-means-in-dockerfile
